'use strict';
// "Storage locations and usage" page: a singleton WebviewPanel in the editor area (opening it again reveals it).
// - buildStorageVm(): a pure function that combines the worker's StorageReport, target folders and open sessions
//   into a view model. All text is localized and formatted here; media/storage.js only renders.
// - Migration commands are generated by migrationPlan() in lib/storage.js and never executed by the extension:
//   "Copy command" writes to the clipboard; "Open in terminal" only calls terminal.sendText(command, false), without pressing Enter.
// - Messages from the webview carry only an entry id, app, plan and command-step name. Paths and commands are always
//   looked up again on the extension side from current data; the webview is not trusted.
// - Before copying or sending to a terminal, open sessions are checked again; if any exist, a modal warning is shown first.

const fs = require('fs');
const os = require('os');
const path = require('path');
const crypto = require('crypto');
const storage = require('./storage');

const VIEW_TYPE = 'agentMonitor.storage';
const APPS = Object.freeze(['claude', 'codex']);
const KINDS = Object.freeze(['symlink', 'env']);
// Copyable command steps (matching MigrationPlan fields)
const PARTS = Object.freeze({
  commands: (p) => p.commands,
  cleanup: (p) => p.cleanup,
  rollback: (p) => p.rollback,
  vscodeSetting: (p) => (p.env && p.env.vscodeSetting) || '',
  shellLine: (p) => (p.env && p.env.shellLine) || '',
  monitorSetting: (p) => p.monitorSetting,
});
// Strings injected into the webview: those the page shows before it receives the first view model
const STORAGE_DICT_PREFIXES = Object.freeze(['storage.page.']);
// Cloud-synced folders (constant writes conflict with syncing)
const SYNCED_RE = /([\\/]Library[\\/]Mobile Documents[\\/]|[\\/]Library[\\/]CloudStorage[\\/]|[\\/](Dropbox|OneDrive|Google Drive|iCloud ?Drive|Box|pCloud Drive)([\\/ (-]|$))/i;
const LIVE_REFRESH_MS = 5000;
const TITLE_MAX = 80;
const DASH = '—';

const fin = (v) => typeof v === 'number' && Number.isFinite(v);

function attr(t) {
  return String(t == null ? '' : t).replace(/[&<>"']/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));
}

/**
 * Byte count -> "932 MB" (decimal units, matching Finder; formatted for the UI language).
 * @param {number} n
 * @param {{ intlLocale?: string }} i18n
 */
function fmtBytes(n, i18n) {
  if (!fin(n) || n < 0) return DASH;
  const units = ['byte', 'kilobyte', 'megabyte', 'gigabyte', 'terabyte', 'petabyte'];
  let v = n;
  let i = 0;
  while (v >= 1000 && i < units.length - 1) { v /= 1000; i++; }
  const digits = i === 0 || v >= 100 ? 0 : 1;
  try {
    return new Intl.NumberFormat((i18n && i18n.intlLocale) || 'en-US',
      { style: 'unit', unit: units[i], unitDisplay: 'short', maximumFractionDigits: digits }).format(v);
  } catch {
    return `${v.toFixed(digits)} ${['B', 'kB', 'MB', 'GB', 'TB', 'PB'][i]}`;
  }
}

// Abbreviate the home directory as ~
function tilde(p, home, platform) {
  const s = String(p || '');
  if (!home || !s) return s;
  if (storage.samePath(s, home, platform)) return '~';
  if (storage.isInside(s, home, platform)) {
    const sep = platform === 'win32' ? '\\' : '/';
    const h = home.replace(/[\\/]+$/, '');
    return '~' + sep + s.slice(h.length + 1);
  }
  return s;
}

const pathApi = (platform) => (platform === 'win32' ? path.win32 : path.posix);

/** User-picked folder F -> where the data goes: F itself if it is named <app>, otherwise F/<app> (so data is never dumped into a drive root) */
function baseFromPick(folder, app, platform) {
  const P = pathApi(platform);
  const f = String(folder || '').replace(/[\\/]+$/, '') || folder;
  const same = platform === 'win32' || platform === 'darwin' ? P.basename(f).toLowerCase() === app : P.basename(f) === app;
  return same ? f : P.join(f, app);
}

// Default file system probe (small synchronous calls on a single directory, on the extension main thread)
const fsProbe = {
  exists: (p) => { try { fs.statSync(p); return true; } catch { return false; } },
  nonEmptyDir: (p) => {
    try { return fs.readdirSync(p).some((n) => n !== '.DS_Store'); } catch { return false; }
  },
};

function revealKey(platform) {
  return platform === 'darwin' ? 'storage.btn.reveal.darwin' : platform === 'win32' ? 'storage.btn.reveal.win32' : 'storage.btn.reveal.linux';
}

// Entry description (hover tooltip)
function itemDesc(app, e, t) {
  if (e.rest) return t('storage.item.rest');
  if (/\.sqlite$/.test(e.name)) return t('storage.item.sqlite');
  const k = `storage.item.${app}.${String(e.name).replace(/^\.+/, '').replace(/[^\w-]/g, '_')}`;
  const s = t(k);
  return s === k ? '' : s;
}

/**
 * Builds the view model. Pure function (the file system probe can be injected).
 * @param {{
 *   report: import('./storage').StorageReport|null, loading?: boolean, error?: string|null,
 *   i18n: any, platform?: string, home?: string, now?: number,
 *   bases?: { claude?: string|null, codex?: string|null },      // user-picked target folders (null = use the suggested one)
 *   live?: Array<{ provider: string, sessionId: string, title?: string }>,
 *   probe?: { exists: (p: string) => boolean, nonEmptyDir: (p: string) => boolean },
 * }} input
 * @returns {{ vm: any, paths: Map<string, string>, plans: Map<string, import('./storage').MigrationPlan> }}
 */
function buildStorageVm(input) {
  const i18n = input.i18n;
  const t = (k, v) => i18n.t(k, v);
  const platform = input.platform || process.platform;
  const P = pathApi(platform);
  const home = input.home || (input.report && input.report.homeDir) || os.homedir();
  const probe = input.probe || fsProbe;
  const r = input.report || null;
  const bases = input.bases || {};
  const live = Array.isArray(input.live) ? input.live : [];
  const paths = new Map();
  const plans = new Map();
  const idOf = new Map();
  const pid = (p) => {
    if (!p) return null;
    if (idOf.has(p)) return idOf.get(p);
    const id = 'p' + paths.size;
    paths.set(id, p);
    idOf.set(p, id);
    return id;
  };
  const show = (p) => tilde(p, home, platform);
  const volumes = (r && r.volumes) || [];
  const volName = (mount) => {
    const v = volumes.find((x) => x.mount === mount);
    return v ? v.name || v.mount : mount;
  };

  const vm = {
    title: t('storage.page.title'),
    intro: t('storage.page.intro'),
    footer: t('storage.page.footer'),
    loading: !!input.loading,
    statusText: '',
    errorText: input.error ? t('storage.page.error', { error: String(input.error) }) : '',
    partialText: r && r.partial ? t('storage.page.partial') : '',
    labels: {
      refresh: t('storage.btn.refresh'),
      reveal: t(revealKey(platform)),
      copyPath: t('storage.btn.copyPath'),
      copy: t('storage.btn.copy'),
      copyOne: t('storage.btn.copyOne'),
      terminal: t('storage.btn.terminal'),
      terminalTip: t('storage.btn.terminal.tip'),
      choose: t('storage.btn.choose'),
      reset: t('storage.btn.reset'),
      colItem: t('storage.col.item'),
      colSize: t('storage.col.size'),
      colFiles: t('storage.col.files'),
      colWhere: t('storage.col.where'),
      plans: t('storage.mig.plans'),
      base: t('storage.mig.base'),
      from: t('storage.mig.from'),
      to: t('storage.mig.to'),
    },
    dirs: [],
    retention: null,
    volumes: null,
    migrate: null,
    notes: null,
  };
  if (input.loading) vm.statusText = t(r ? 'storage.page.refreshing' : 'storage.page.loading');
  else if (r && fin(r.at)) vm.statusText = t('storage.page.scanned', { time: i18n.fmtClock ? i18n.fmtClock(r.at, input.now || Date.now()) : new Date(r.at).toLocaleTimeString() });
  if (!r) return { vm, paths, plans };

  // ---------- The two data directories ----------
  for (const app of APPS) {
    const d = r[app];
    if (!d) continue;
    const envName = storage.ENV_VAR[app];
    const dvm = {
      app,
      heading: t('storage.dir.' + app),
      pathText: show(d.dir),
      pathId: d.exists ? pid(d.dir) : null,
      sourceText: d.dirSource === 'env' ? t('storage.dir.source.env', { name: envName })
        : d.dirSource === 'setting' ? t('storage.dir.source.setting') : t('storage.dir.source.default'),
      totalText: d.exists ? t('storage.dir.total', { size: fmtBytes(d.totalBytes, i18n), files: i18n.fmtNum(d.totalFiles) }) : '',
      missingText: !d.exists ? t('storage.dir.missing') : '',
      linkText: d.isSymlink && d.symlinkTarget ? t('storage.dir.linked', { target: show(d.symlinkTarget) }) : '',
      errorText: d.error ? t(d.error === 'TARGET_MISSING' ? 'storage.entry.targetMissing' : 'storage.entry.error', { code: d.error }) : '',
      entries: [],
    };
    for (const e of d.entries || []) {
      const label = e.rest ? t('storage.entry.rest', { n: i18n.fmtNum(e.count || 0) }) : e.name;
      let where = '';
      let tone = '';
      if (!e.exists) where = e.error ? t('storage.entry.error', { code: e.error }) : t('storage.entry.missing');
      else if (e.error === 'TARGET_MISSING') { where = t('storage.entry.targetMissing'); tone = 'error'; }
      else if (e.error) { where = t('storage.entry.error', { code: e.error }); tone = 'error'; }
      else if (e.sameAs) where = t('storage.entry.sameAs', { name: e.sameAs });
      else if (e.volume && d.volume && e.volume !== d.volume) where = t('storage.entry.onVolume', { volume: volName(e.volume) });
      if (e.exists && e.outside) where = [t('storage.entry.outside'), where].filter(Boolean).join(' · ');
      if (e.errors && !tone) tone = 'warn';
      const tip = [
        itemDesc(app, e, t),
        e.rest ? '' : e.path,
        e.rest && e.top && e.top.length ? t('storage.entry.largest', { list: e.top.map((x) => `${x.name} ${fmtBytes(x.bytes, i18n)}`).join(', ') }) : '',
        e.errors ? t('storage.entry.errors', { n: i18n.fmtNum(e.errors) }) : '',
        e.partial ? t('storage.page.partial') : '',
      ].filter(Boolean).join('\n');
      dvm.entries.push({
        key: app + ':' + (e.rest ? '*' : e.name),
        name: label,
        rest: !!e.rest,
        exists: !!e.exists,
        sizeText: e.exists && !e.sameAs ? fmtBytes(e.bytes, i18n) + (e.partial ? '+' : '') : DASH,
        // The "Files" column shows only the number (the column header says what it is), avoiding "1 files" in English
        filesText: e.exists && !e.sameAs && e.kind === 'dir' ? i18n.fmtNum(e.files) : '',
        filesTip: e.exists && !e.sameAs && e.kind === 'dir' ? t('storage.col.files') + ': ' + i18n.fmtNum(e.files) : '',
        link: e.isSymlink && e.symlinkTarget ? { text: t('storage.entry.link', { target: show(e.symlinkTarget) }), id: pid(e.symlinkTarget) } : null,
        whereText: where,
        errorsText: e.errors ? t('storage.entry.errors', { n: i18n.fmtNum(e.errors) }) : '',
        tone,
        pathId: e.exists && !e.rest ? pid(e.path) : null,
        tip,
      });
    }
    vm.dirs.push(dvm);
  }

  // ---------- Retention days ----------
  if (r.claude) {
    const n = r.cleanupPeriodDays;
    vm.retention = {
      label: t('storage.retention.label'),
      text: fin(n) ? t('storage.retention.value', { n: i18n.fmtNum(n) }) : t('storage.retention.default'),
      tip: t('storage.retention.tip', { path: show(P.join(r.claude.dir, 'settings.json')) }),
    };
  }

  // ---------- Target folders ----------
  const targetOf = {};
  for (const app of APPS) {
    const d = r[app];
    if (!d || !d.exists) continue;
    const custom = bases[app] || null;
    const suggested = storage.defaultBase(app, volumes, d.volume, platform);
    targetOf[app] = { base: custom || suggested, custom: !!custom, suggested };
  }

  // ---------- Volumes ----------
  const suggestedMounts = new Set();
  for (const app of APPS) {
    const x = targetOf[app];
    if (x && x.suggested) suggestedMounts.add(storage.volumeOf(x.suggested, volumes, platform));
  }
  vm.volumes = {
    heading: t('storage.vol.heading'),
    rows: volumes.map((v) => {
      const used = v.totalBytes > 0 ? Math.max(0, Math.min(1, 1 - v.freeBytes / v.totalBytes)) : null;
      const tags = [];
      if (v.system) tags.push(t('storage.vol.system'));
      if (v.writable === false) tags.push(t('storage.vol.readOnly'));
      if (r.claude && r.claude.volume === v.mount) tags.push(t('storage.vol.claude'));
      if (r.codex && r.codex.volume === v.mount) tags.push(t('storage.vol.codex'));
      if (suggestedMounts.has(v.mount)) tags.push(t('storage.vol.suggested'));
      return {
        key: 'v:' + v.mount,
        name: v.name || v.mount,
        // Skip the mount point when it equals the name (e.g. C: and C:\ on Windows)
        mountText: v.name && v.name !== v.mount.replace(/[\\/]+$/, '') ? v.mount : '',
        freeText: t('storage.vol.free', { free: fmtBytes(v.freeBytes, i18n), total: fmtBytes(v.totalBytes, i18n) }),
        usedPct: used == null ? null : Math.round(used * 100),
        usedText: used == null ? '' : t('storage.vol.used', { pct: i18n.fmtPct(used) }),
        meterLabel: t('storage.vol.meter', { name: v.name || v.mount }),
        low: used != null && used >= 0.9,
        tags,
        pathId: pid(v.mount),
      };
    }),
  };

  // ---------- Migration reference ----------
  const cards = [];
  for (const app of APPS) {
    const d = r[app];
    const tg = targetOf[app];
    if (!d || !d.exists || !tg) continue;
    const sub = storage.MIGRATE_SUB[app];
    const entry = (d.entries || []).find((e) => e.name === sub && !e.rest) || null;
    const appName = t('storage.app.' + app);
    const envName = storage.ENV_VAR[app];
    const liveHere = live.filter((s) => s && s.provider === app);
    const card = {
      app,
      heading: t('storage.mig.' + app, { sub }),
      sizeText: entry && entry.exists ? fmtBytes(entry.bytes, i18n) : '',
      live: liveHere.length ? {
        text: t('storage.live.' + app, { n: i18n.fmtNum(liveHere.length) }),
        items: liveHere.map((s) => clip(s.title || s.sessionId || '')),
      } : null,
      target: {
        text: tg.base ? show(tg.base) : '',
        id: tg.base && probe.exists(tg.base) ? pid(tg.base) : null,
        note: tg.base ? t(tg.custom ? 'storage.mig.custom' : 'storage.mig.suggested') : t('storage.mig.noTarget'),
        custom: tg.custom,
        hint: t('storage.mig.toHint', { app }),
      },
      warnings: [],
      plans: [],
    };
    // Warnings about the target as a whole
    const synced = tg.base && SYNCED_RE.test(tg.base);
    if (synced) card.warnings.push(t('storage.target.synced'));
    const tVol = tg.base ? storage.volumeOf(tg.base, volumes, platform) : null;
    const tVolInfo = volumes.find((v) => v.mount === tVol) || null;
    if (tg.base && tVolInfo && tVolInfo.writable === false) card.warnings.push(t('storage.target.readOnly'));
    if (tg.base && tVol && d.volume && tVol === d.volume) card.warnings.push(t('storage.target.sameDisk'));
    if (tg.base && tVol && tVol !== '/' && !/^[A-Za-z]:\\$/.test(tVol) && !probe.exists(tVol)) card.warnings.push(t('storage.target.notMounted', { path: show(tVol) }));

    for (const kind of KINDS) {
      const pvm = {
        kind,
        label: t(kind === 'symlink' ? (platform === 'win32' ? 'storage.mig.planA.win' : 'storage.mig.planA') : 'storage.mig.planB', { sub, name: envName }),
        badge: kind === 'symlink' ? t('storage.mig.recommended') : t('storage.mig.official'),
        desc: t(kind === 'symlink' ? 'storage.mig.planA.desc' : 'storage.mig.planB.desc', { sub, name: envName, app: appName }),
        info: '',
        infoId: null,
        fromText: '',
        toText: '',
        errorText: '',
        warnings: [],
        steps: [],
        notes: [],
      };
      card.plans.push(pvm);
      if (kind === 'symlink') {
        if (!entry || !entry.exists) { pvm.info = t('storage.mig.nothing', { sub }); continue; }
        if (entry.isSymlink) {
          pvm.info = t('storage.mig.linked', { sub, target: show(entry.symlinkTarget || entry.realPath || '') });
          pvm.infoId = pid(entry.symlinkTarget || entry.realPath);
          continue;
        }
      }
      if (!tg.base) { pvm.errorText = t('storage.mig.noTarget'); continue; }
      const source = kind === 'symlink' ? entry.path : d.dir;
      const target = kind === 'symlink' ? P.join(tg.base, sub) : tg.base;
      const plan = storage.migrationPlan({ platform, kind, app, source, target, homeDir: home, i18n });
      if (!plan.ok) { pvm.errorText = t('storage.plan.error.' + plan.error); continue; }
      plans.set(app + '|' + kind, plan);
      pvm.fromText = show(source);
      pvm.toText = show(target);
      // Plan-specific target warnings: existing files, not enough space
      if (probe.nonEmptyDir(target)) pvm.warnings.push(t('storage.target.notEmpty', { path: show(target) }));
      const need = kind === 'symlink' ? entry.bytes : d.totalBytes;
      if (tVolInfo && fin(need) && need > 0 && tVolInfo.freeBytes < need * 1.05) {
        pvm.warnings.push(t('storage.target.noSpace', { need: fmtBytes(need, i18n), free: fmtBytes(tVolInfo.freeBytes, i18n) }));
      }
      const step = (key, vars, part, actions) => ({
        text: t(key, vars),
        code: part ? PARTS[part](plan) : '',
        part: part || null,
        actions: part ? actions || ['copy'] : [],
      });
      const S = pvm.steps;
      S.push(step(app === 'codex' ? 'storage.step.close.codex' : 'storage.step.close.claude'));
      if (kind === 'symlink') {
        S.push(step('storage.step.run', { sub, target: show(target) }, 'commands', ['copy', 'terminal']));
        S.push(step('storage.step.check'));
        S.push(step('storage.step.cleanup', null, 'cleanup'));
        S.push(step('storage.step.rollback', null, 'rollback'));
      } else {
        S.push(step('storage.step.copy', { target: show(target) }, 'commands', ['copy', 'terminal']));
        if (plan.env && plan.env.vscodeSetting) S.push(step('storage.step.envVscode', { name: envName }, 'vscodeSetting'));
        S.push(step(platform === 'win32' ? 'storage.step.envWin' : app === 'codex' ? 'storage.step.envShell.codex' : 'storage.step.envShell',
          { name: envName }, 'shellLine'));
        S.push(step('storage.step.monitor', null, 'monitorSetting'));
        S.push(step(app === 'claude' ? 'storage.step.restart.claude' : 'storage.step.restart.codex'));
        S.push(step('storage.step.cleanup', null, 'cleanup'));
        S.push(step('storage.step.rollback.env', { name: envName }, 'rollback'));
      }
      pvm.notes = plan.notes.slice();
    }
    cards.push(card);
  }
  vm.migrate = {
    heading: t('storage.mig.heading'),
    why: t('storage.mig.why'),
    // Migration plans are reference only: a prominent disclaimer, and the copy / send-to-terminal buttons are enabled only after the user ticks the confirmation
    disclaimer: {
      title: t('storage.disclaimer.title'),
      items: [t('storage.disclaimer.reference'), t('storage.page.neverRuns'), t('storage.disclaimer.check'), t('storage.disclaimer.risk')],
      ack: t('storage.disclaimer.ack'),
      locked: t('storage.disclaimer.locked'),
    },
    cards,
  };

  // ---------- Notes (listed in full) ----------
  const notes = [
    t('storage.note.mount'),
    t('storage.note.sync'),
    t('storage.note.noSessions'),
    t('storage.note.keepBak'),
    t(platform === 'win32' ? 'storage.note.windows.here' : 'storage.note.windows'),
    t('storage.note.memory'),
  ];
  vm.notes = { heading: t('storage.notes.heading'), items: notes };
  return { vm, paths, plans };
}

function clip(s) {
  const v = String(s || '').replace(/\s+/g, ' ').trim();
  return v.length > TITLE_MAX ? v.slice(0, TITLE_MAX - 1) + '…' : v;
}

// ---------------------------------------------------------------------------
// Page HTML (pure function, shared by the preview page and the extension)
// ---------------------------------------------------------------------------

/**
 * @param {{ cspSource: string, asset: (p: string) => string, nonce: string, i18n: any }} o
 * @returns {string}
 */
function storageHtml({ cspSource, asset, nonce, i18n }) {
  const t = (k, vars) => attr(i18n.t(k, vars));
  const csp = [
    "default-src 'none'",
    `style-src ${cspSource}`,
    `font-src ${cspSource}`,
    `script-src 'nonce-${nonce}'`,
  ].join('; ');
  const l10n = i18n.webviewJson(STORAGE_DICT_PREFIXES);
  return `<!DOCTYPE html>
<html lang="${attr(i18n.intlLocale || 'en')}">
<head>
<meta charset="UTF-8">
<meta http-equiv="Content-Security-Policy" content="${attr(csp)}">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link rel="stylesheet" href="${attr(asset('codicons/codicon.css'))}">
<link rel="stylesheet" href="${attr(asset('storage.css'))}">
<title>${t('storage.page.title')}</title>
<script type="application/json" id="l10n">${l10n}</script>
</head>
<body>
<main class="page">
  <header class="p-head">
    <h1 id="title">${t('storage.page.title')}</h1>
    <span id="status" class="muted" role="status">${t('storage.page.loading')}</span>
    <span class="spacer"></span>
    <button type="button" id="refresh" class="btn secondary" data-act="refresh"><i class="codicon codicon-refresh" aria-hidden="true"></i><span>${t('storage.btn.refresh')}</span></button>
  </header>
  <div id="root"></div>
</main>
<script nonce="${attr(nonce)}" src="${attr(asset('storage.js'))}"></script>
</body>
</html>`;
}

// ---------------------------------------------------------------------------
// WebviewPanel
// ---------------------------------------------------------------------------

let current = null;

class StoragePanel {
  /**
   * @param {any} context ExtensionContext
   * @param {{ requestStorage: (force: boolean) => Promise<any>, liveSessions: () => Array<{ provider: string, sessionId: string, title?: string }>,
   *   i18n: any, platform?: string, vscode?: any, log?: (s: string) => void, home?: string }} deps
   */
  constructor(context, deps) {
    this.vscode = deps.vscode || require('vscode');
    this.context = context;
    this.deps = deps;
    this.i18n = deps.i18n;
    this.platform = deps.platform || process.platform;
    this.home = deps.home || os.homedir();
    this.log = typeof deps.log === 'function' ? deps.log : () => {};
    this.panel = null;
    this.ready = false;
    this.disposed = false;
    this.report = null;
    this.loading = false;
    this.error = null;
    this.bases = { claude: null, codex: null };
    this.paths = new Map();
    this.plans = new Map();
    this.lastJson = '';
    this.seq = 0;
    this.timer = null;
    this.disposables = [];
  }

  t(k, v) { return this.i18n.t(k, v); }

  open() {
    const vscode = this.vscode;
    const media = vscode.Uri.joinPath(this.context.extensionUri, 'media');
    const panel = vscode.window.createWebviewPanel(VIEW_TYPE, this.t('storage.page.title'),
      vscode.ViewColumn ? vscode.ViewColumn.Active : -1,
      { enableScripts: true, localResourceRoots: [media], retainContextWhenHidden: false });
    this.panel = panel;
    try { panel.iconPath = vscode.Uri.joinPath(media, 'icon.png'); } catch { /* ignore */ }
    const nonce = crypto.randomBytes(16).toString('base64');
    panel.webview.html = storageHtml({
      cspSource: panel.webview.cspSource,
      asset: (p) => panel.webview.asWebviewUri(vscode.Uri.joinPath(media, ...p.split('/'))).toString(),
      nonce,
      i18n: this.i18n,
    });
    this.disposables.push(
      panel.webview.onDidReceiveMessage((m) => {
        Promise.resolve().then(() => this.onMessage(m)).catch((err) => this.log('storage view: ' + ((err && err.stack) || err)));
      }),
      panel.onDidDispose(() => this.dispose()),
    );
    if (typeof panel.onDidChangeViewState === 'function') {
      this.disposables.push(panel.onDidChangeViewState(() => { if (!panel.visible) this.ready = false; }));
    }
    // Open sessions change over time: while the page is visible, recompute from the latest snapshot every 5 s (nothing is posted if unchanged)
    this.timer = setInterval(() => { if (this.panel && this.panel.visible !== false) this.post(); }, LIVE_REFRESH_MS);
    if (this.timer && typeof this.timer.unref === 'function') this.timer.unref();
    this.load(false);
    return this;
  }

  reveal() {
    if (this.panel) {
      try { this.panel.reveal(); } catch { /* ignore */ }
    }
    this.load(false);
  }

  liveSessions() {
    try {
      const list = this.deps.liveSessions ? this.deps.liveSessions() : [];
      return Array.isArray(list) ? list.filter((s) => s && typeof s === 'object') : [];
    } catch {
      return [];
    }
  }

  /** Request a usage report (force: bypass the worker's 10-minute cache) */
  load(force) {
    const seq = ++this.seq;
    this.loading = true;
    this.error = null;
    this.post();
    let p;
    try { p = Promise.resolve(this.deps.requestStorage(!!force)); } catch (err) { p = Promise.reject(err); }
    return p.then((rep) => {
      if (seq !== this.seq || this.disposed) return;
      if (rep && typeof rep === 'object') this.report = rep;
      this.loading = false;
      this.post();
    }, (err) => {
      if (seq !== this.seq || this.disposed) return;
      this.loading = false;
      this.error = String((err && err.message) || err);
      this.post();
    });
  }

  build() {
    const out = buildStorageVm({
      report: this.report, loading: this.loading, error: this.error, i18n: this.i18n,
      platform: this.platform, home: this.home, bases: this.bases, live: this.liveSessions(), now: Date.now(),
    });
    this.paths = out.paths;
    this.plans = out.plans;
    return out.vm;
  }

  post() {
    if (!this.panel || !this.ready || this.disposed) return;
    const vm = this.build();
    const json = JSON.stringify(vm);
    if (json === this.lastJson) return;
    this.lastJson = json;
    this.panel.webview.postMessage({ type: 'vm', vm });
  }

  async confirmLive(app) {
    const list = this.liveSessions().filter((s) => s.provider === app);
    if (!list.length) return true;
    const cont = this.t('storage.live.continue');
    const pick = await this.vscode.window.showWarningMessage(
      this.t('storage.live.confirm', { app: this.t('storage.app.' + app), n: this.i18n.fmtNum(list.length) }),
      { modal: true, detail: list.map((s) => '· ' + clip(s.title || s.sessionId)).join('\n') },
      cont,
    );
    return pick === cont;
  }

  // Migration commands are only a reference: the message carries ack only if the page checkbox was ticked; without it (old page, button bypassed) show a dialog so the user confirms first
  async confirmReference(m) {
    if (m && m.ack === true) return true;
    const ok = this.t('storage.disclaimer.continue');
    const pick = await this.vscode.window.showWarningMessage(this.t('storage.disclaimer.confirm'), { modal: true }, ok);
    return pick === ok;
  }

  planFor(m) {
    if (!m || !APPS.includes(m.app) || !KINDS.includes(m.kind)) return null;
    this.build(); // rebuild from current data so the commands match the latest target
    return this.plans.get(m.app + '|' + m.kind) || null;
  }

  async onMessage(m) {
    if (!m || typeof m.type !== 'string') return;
    const vscode = this.vscode;
    switch (m.type) {
      case 'ready':
        this.ready = true;
        this.lastJson = '';
        this.post();
        return;
      case 'refresh':
        this.load(true);
        return;
      case 'reveal': {
        const p = this.paths.get(m.id);
        if (!p) return;
        if (!fsProbe.exists(p)) { vscode.window.showWarningMessage(this.t('storage.missing', { path: tilde(p, this.home, this.platform) })); return; }
        await vscode.commands.executeCommand('revealFileInOS', vscode.Uri.file(p));
        return;
      }
      case 'copyPath': {
        const p = this.paths.get(m.id);
        if (!p) return;
        await vscode.env.clipboard.writeText(p);
        vscode.window.showInformationMessage(this.t('storage.copied.path'));
        return;
      }
      case 'pickTarget': {
        if (!APPS.includes(m.app)) return;
        const cur = this.bases[m.app] || (this.report && this.report[m.app] ? storage.defaultBase(m.app, this.report.volumes || [], this.report[m.app].volume, this.platform) : null);
        const start = cur ? pathApi(this.platform).dirname(cur) : null;
        const res = await vscode.window.showOpenDialog({
          canSelectFiles: false, canSelectFolders: true, canSelectMany: false,
          openLabel: this.t('storage.pick.open'),
          title: this.t('storage.pick.title', { app: this.t('storage.app.' + m.app) }),
          ...(start && fsProbe.exists(start) ? { defaultUri: vscode.Uri.file(start) } : {}),
        });
        const f = res && res[0] && res[0].fsPath;
        if (!f) return;
        this.bases[m.app] = baseFromPick(f, m.app, this.platform);
        this.post();
        return;
      }
      case 'resetTarget':
        if (!APPS.includes(m.app)) return;
        this.bases[m.app] = null;
        this.post();
        return;
      case 'copy': {
        const plan = this.planFor(m);
        const get = Object.prototype.hasOwnProperty.call(PARTS, m.part) ? PARTS[m.part] : null;
        const text = plan && get ? get(plan) : '';
        if (!text) return;
        if (!(await this.confirmReference(m))) return;
        if (m.part === 'commands' && !(await this.confirmLive(m.app))) return;
        await vscode.env.clipboard.writeText(text);
        vscode.window.showInformationMessage(this.t(m.part === 'commands' || m.part === 'cleanup' || m.part === 'rollback' ? 'storage.copied.command' : 'storage.copied.text'));
        return;
      }
      case 'terminal': {
        const plan = this.planFor(m);
        if (!plan || !plan.oneLine) return;
        if (!(await this.confirmReference(m))) return;
        if (!(await this.confirmLive(m.app))) return;
        const opts = { name: this.t('storage.terminal.name') };
        // On Windows the commands are PowerShell syntax
        if (this.platform === 'win32') opts.shellPath = 'powershell.exe';
        const term = vscode.window.createTerminal(opts);
        term.show();
        // Only paste into the terminal without pressing Enter (the second argument must be false); the user reviews and runs it
        term.sendText(plan.oneLine, false);
        vscode.window.showInformationMessage(this.t('storage.terminal.sent'));
        return;
      }
      default:
    }
  }

  dispose() {
    if (this.disposed) return;
    this.disposed = true;
    clearInterval(this.timer);
    this.timer = null;
    for (const d of this.disposables.splice(0)) { try { d.dispose(); } catch { /* ignore */ } }
    const p = this.panel;
    this.panel = null;
    this.ready = false;
    if (p) { try { p.dispose(); } catch { /* ignore */ } }
    if (current === this) current = null;
  }
}

/**
 * Opens the "Storage locations and usage" page (singleton: if already open, reveal it and refresh once from cache).
 * @param {any} context ExtensionContext
 * @param {{ requestStorage: (force: boolean) => Promise<any>, liveSessions: () => Array<{ provider: string, sessionId: string, title?: string }>,
 *   i18n: any, platform?: string, vscode?: any, log?: (s: string) => void, home?: string }} deps
 * @returns {StoragePanel}
 */
function openStorageView(context, deps) {
  if (current && !current.disposed) {
    current.deps = { ...current.deps, ...deps };
    current.reveal();
    return current;
  }
  current = new StoragePanel(context, deps);
  return current.open();
}

module.exports = {
  VIEW_TYPE, STORAGE_DICT_PREFIXES,
  openStorageView, StoragePanel, buildStorageVm, storageHtml, fmtBytes,
  _internal: { tilde, baseFromPick, clip, SYNCED_RE },
};
